/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_phpdt_internal_debug_core_Environment */

#ifndef _Included_net_sourceforge_phpdt_internal_debug_core_Environment
#define _Included_net_sourceforge_phpdt_internal_debug_core_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_phpdt_internal_debug_core_Environment
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sourceforge_phpdt_internal_debug_core_Environment_getenv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sourceforge_phpdt_internal_debug_core_Environment
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sourceforge_phpdt_internal_debug_core_Environment_setenv
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
